# number of months of historical data to average over to get factors
observed_months: 12
observed_months_fill_rate: 4

# Revenue per Mille, agreed contractually with Admarketplace.
CPM:
  AU: 
    tiles_1_and_2: 0.099
    tile3: 0
  BR: 
    tiles_1_and_2: 0.066
    tile3: 0
  CA: 
    tiles_1_and_2: 0.330
    tile3: 0
  DE: 
    tiles_1_and_2: 0.528
    tile3: 0.187
  ES: 
    tiles_1_and_2: 0.198
    tile3: 0.066
  FR: 
    tiles_1_and_2: 0.231
    tile3: 0.077
  GB: 
    tiles_1_and_2: 0.385
    tile3: 0.132
  IN: 
    tiles_1_and_2: 0.044
    tile3: 0
  IT: 
    tiles_1_and_2: 0.363
    tile3: 0.132
  JP:
    tiles_1_and_2: 0.02
    tile3: 0
  MX:
    tiles_1_and_2: 0.209
    tile3: 0
  US: 
    tiles_1_and_2: 0.627
    tile3: 0.220
  BE: 
    tiles_1_and_2: 0.050
    tile3: 0
  AT:
    tiles_1_and_2: 0.05
    tile3: 0
  PL:
    tiles_1_and_2: 0.050
    tile3: 0
  NL:
    tiles_1_and_2: 0.05
    tile3: 0
  CH: 
    tiles_1_and_2: 0.050
    tile3: 0 #switzerland


# elgilibity rules for different product/platform combos
elgibility:
  tiles:
    mobile:
      function_call: IsElgibleTilesMobile(os_grouped, app_version_major, country, submission_date)
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleTilesMobile(os STRING,
                                              version NUMERIC,
                                              country STRING,
                                              submission_date DATE)
        RETURNS BOOL
        AS ((os = "Android"
                AND  version > 100
                AND (
                    (country = "US" AND submission_date >= "2022-09-20")
                    OR (country = "DE" AND submission_date >= "2022-12-05")
                    OR (country IN ("BR", "CA", "ES",
                                        "FR", "GB", "IN", "AU")
                            AND submission_date >= "2023-05-15")))
            OR (os = "iOS"
                AND version > 101
                AND (
                    (country = "US"
                        AND submission_date >= "2022-10-04")
                    OR (country = "DE"
                        AND submission_date >= "2022-12-05")
                    OR (country IN ("BR", "CA", "ES",
                                        "FR", "GB", "IN", "AU")
                        AND submission_date >= "2023-05-15")
                ))) ;
    desktop:
      function_call: IsElgibleTilesDesktop(app_name, app_version_major, country, submission_date)
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleTilesDesktop(app_name STRING,
                                              version NUMERIC,
                                              country STRING,
                                              submission_date DATE)
        RETURNS BOOL
        AS (app_name = "Firefox Desktop"
            AND (
              -- desktop tiles default on
              (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN UNNEST(
                  ["AU", "BR", "CA", "DE", "ES", "FR", "GB", "IN", "IT", "MX", "US"]
                )
              )
              OR
              -- Japan desktop now default on
              (
                submission_date >= "2022-01-25"
                AND version > 92
                AND country = "JP"
              )
              OR
              -- 2025 baseline expansion countries
                            (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("BE","AT","PL","NL","SE","CH")
              )
            ));

# impute new markets
new_markets:
  BE:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  AT: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  PL: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  NL: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  SE: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  CH: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT

# specify values used for product column
product:
  - "tile"
  - "tile direct sales"
# specify the output dataset and table
# to write the data to
output:
  test:
    project: moz-fx-data-bq-data-science
    dataset: jsnyder
    table: tiles_monthly_v1_test
  prod:
    project: moz-fx-data-shared-prod
    dataset: ads_derived
    table: tiles_monthly_v1
