# number of months of historical data to average over to get factors
observed_months: 12
observed_months_fill_rate: 4

# Revenue per Mille, agreed contractually with Admarketplace.
CPM:
  AU: 
    tiles_1_and_2: 0.099
    tile3: .077
  BR: 
    tiles_1_and_2: 0.066
    tile3: 0.019
  CA: 
    tiles_1_and_2: 0.330
    tile3: 0.299
  DE: 
    tiles_1_and_2: 0.528
    tile3: 0.187
  ES: 
    tiles_1_and_2: 0.198
    tile3: 0.066
  FR: 
    tiles_1_and_2: 0.231
    tile3: 0.077
  GB: 
    tiles_1_and_2: 0.385
    tile3: 0.132
  IN: 
    tiles_1_and_2: 0.044
    tile3: 0
  IT: 
    tiles_1_and_2: 0.363
    tile3: 0.132
  JP:
    tiles_1_and_2: 0.022
    tile3: 0.0072
  MX:
    tiles_1_and_2: 0.209
    tile3: 0.0649
  US: 
    tiles_1_and_2: 0.627
    tile3: 0.220
  BE: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  AT:
    tiles_1_and_2: 0.050
    tile3: 0.016
  PL:
    tiles_1_and_2: 0.050
    tile3: 0.016
  NL:
    tiles_1_and_2: 0.050
    tile3: 0.016
  SE: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  CH: 
    tiles_1_and_2: 0.050
    tile3: 0.016 #switzerland
  FI:  # stretch EU countries start here
    tiles_1_and_2: 0.050
    tile3: 0.016 
  NO:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  PT:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  GR:
    tiles_1_and_2: 0.050
    tile3: 0.016  
  CZ:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  HU:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  DK:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  TR:
    tiles_1_and_2: 0.050
    tile3: 0.016 
  KR: # Asia/Pacific stretch countries start here
    tiles_1_and_2: 0.050
    tile3: 0.016 
  SG: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  ID: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  PH: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  VN: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  HK: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  AR: # Latin America stretch countries start here
    tiles_1_and_2: 0.050
    tile3: 0.016 
  CL: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  PE: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  CO: 
    tiles_1_and_2: 0.050
    tile3: 0.016
  VE:  
    tiles_1_and_2: 0.050
    tile3: 0.016

# list of direct allocation time windows
# each element in the list is a timeframe
# for the countries specified in markets 
# for which the fraction in allocation is sent
# to Ad Marketplace.  start_month and end_month
# specify the start and end of the time window inclusively
# Both are optional, and the earliest and latest values
# in the data are used to replace them respectively if left out
direct_allocations:
  - markets:
      DE: 1.00
      GB: 1.00
      US: 1.00
      FR: 1.00
      IT: 1.00
      ES: 1.00
    allocation: .05
    start_month: 2025-01
    positions:
      - 3


# elgilibity rules for different product/platform combos
elgibility:
  tiles:
    mobile:
      function_call: IsElgibleTilesMobile(os_grouped, app_version_major, country, submission_date)
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleTilesMobile(os STRING,
                                              version NUMERIC,
                                              country STRING,
                                              submission_date DATE)
        RETURNS BOOL
        AS ((os = "Android"
                AND  version > 100
                AND (
                    (country = "US" AND submission_date >= "2022-09-20")
                    OR (country = "DE" AND submission_date >= "2022-12-05")
                    OR (country IN ("BR", "CA", "ES",
                                        "FR", "GB", "IN", "AU")
                            AND submission_date >= "2023-05-15")))
            OR (os = "iOS"
                AND version > 101
                AND (
                    (country = "US"
                        AND submission_date >= "2022-10-04")
                    OR (country = "DE"
                        AND submission_date >= "2022-12-05")
                    OR (country IN ("BR", "CA", "ES",
                                        "FR", "GB", "IN", "AU")
                        AND submission_date >= "2023-05-15")
                ))) ;
    desktop:
      function_call: IsElgibleTilesDesktop(app_name, app_version_major, country, submission_date)
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleTilesDesktop(app_name STRING,
                                              version NUMERIC,
                                              country STRING,
                                              submission_date DATE)
        RETURNS BOOL
        AS (app_name = "Firefox Desktop"
            AND (
              -- desktop tiles default on
              (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("AU", "BR", "CA", "DE", "ES", "FR", "GB", "IN", "IT", "MX", "US")
              )
              OR
              -- Japan desktop now default on
              (
                submission_date >= "2022-01-25"
                AND version > 92
                AND country = "JP"
              )
              OR
              -- 2025 baseline expansion countries
                            (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("BE","AT","PL","NL","SE","CH")
              )
              OR
              -- 2025 stretch EU
              (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("FI","NO","PT","GR","CZ","HU","DK","TR")
              )
              OR
              -- 2025 stretch asia/pacific
                            (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("KR","SG","ID","PH","VN","HK")
              )
              OR
              -- 2025 stretch americas
                            (
                submission_date >= "2021-09-07"
                AND version > 92
                AND country IN ("AR","CL","PE","CO","VE")
              )
            ));

# impute new markets
new_markets:
  BE:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  AT: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  PL: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  NL: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  SE: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  CH: 
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  FI:  # EU stretch starts here
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  NO:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  PT:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  GR:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  CZ:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  HU:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  DK:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  TR:
    countries_to_use: 
      - DE
      - ES
      - FR
      - GB
      - IT
  KR:  # asia pacific stretch starts here
    countries_to_use:
      - JP
      - AU
      - IN
  SG:
    countries_to_use:
      - JP
      - AU
      - IN
  ID:
    countries_to_use:
      - JP
      - AU
      - IN
  PH: 
    countries_to_use:
      - JP
      - AU
      - IN
  VN: 
    countries_to_use:
      - JP
      - AU
      - IN
  HK: 
    countries_to_use:
      - JP
      - AU
      - IN
  AR: 
    countries_to_use:
      - MX
      - BR
  CL: 
    countries_to_use:
      - MX
      - BR
  PE: 
    countries_to_use:
      - MX
      - BR
  CO: 
    countries_to_use:
      - MX
      - BR
  VE: 
    countries_to_use:
      - MX
      - BR

# specify values used for product column
product:
  - "tile"
  - "tile direct sales"
# specify the output dataset and table
# to write the data to
output:
  test:
    project: moz-fx-data-bq-data-science
    dataset: jsnyder
    table: tiles_monthly_v1_test
  prod:
    project: moz-fx-data-shared-prod
    dataset: ads_derived
    table: tiles_monthly_v1