# start date to pull data for KPI forecast
kpi_forecast_start_date: "2019-01-01"

# elgilibity rules for different product/platform combos
eligibility:
  native:
    mobile:
      function_call: IsElgibleNativeMobile()
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleNativeMobile()
        RETURNS BOOL
        AS (False) ;
    desktop:
      function_call: IsElgibleNativeDesktop()
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleNativeDesktop()
        RETURNS BOOL
        AS (True) ;

# countries to run the forecast on
countries:
  - DE
  - GB
  - CA
  - FR
  - ES
  - IT
  - US
