# elgilibity rules for different product/platform combos
elgibility:
  native:
    mobile:
      function_call: IsElgibleNativeMobile()
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleNativeMobile()
        RETURNS BOOL
        AS (False) ;
    desktop:
      function_call: IsElgibleNativeDesktop()
      bq_function: >
        CREATE TEMP FUNCTION IsElgibleNativeDesktop()
        RETURNS BOOL
        AS (True) ;

# specify the output database and table
# to write the data to
output:
  test:
    project: moz-fx-data-bq-data-science
    database: jsnyder
    table: native_forecast
  prod:
    project: mozdata
    database: revenue_cat3_analysis
    table: native_forecast
