# countries to include in forecast
countries:
  - AU
  - BR
  - CA
  - DE
  - ES
  - FR
  - GB
  - IN
  - US

elgibility:
  - segment:
      platform: mobile
      forecast: tiles
    function_call: IsElgibleTilesMobile(os_grouped, app_version_major, country, submission_date)
    bq_function: >
      CREATE TEMP FUNCTION IsElgibleTilesMobile(os STRING,
                                            version NUMERIC,
                                            country STRING,
                                            submission_date DATE)
      RETURNS BOOL
      AS ((os = "Android"
              AND  version > 100
              AND (
                  (country = "US" AND submission_date >= "2022-09-20")
                  OR (country = "DE" AND submission_date >= "2022-12-05")
                  OR (country IN ("BR", "CA", "ES",
                                      "FR", "GB", "IN", "AU")
                          AND submission_date >= "2023-05-15")))
          OR (os = "iOS"
              AND version > 101
              AND (
                  (country = "US"
                      AND submission_date >= "2022-10-04")
                  OR (country = "DE"
                      AND submission_date >= "2022-12-05")
                  OR (country IN ("BR", "CA", "ES",
                                      "FR", "GB", "IN", "AU")
                      AND submission_date >= "2023-05-15")
              ))) ;

# advertisers to exclude when gathering tile interaction data
excluded_advertisers:
  - "o=45:a"
  - yandex

output:
  test:
    project: moz-fx-data-bq-data-science
    database: jsnyder
    table: mobile_tiles
  prod:
    project: mozdata
    database: revenue_cat3_analysis
    table: amp_rpm_forecasts_mobile
