# countries to include in forecast
countries:
  - AU
  - BR
  - CA
  - DE
  - ES
  - FR
  - GB
  - IN
  - US

# advertisers to exclude when gathering tile interaction data
excluded_advertisers:
  - "o=45:a"
  - yandex

output:
  test:
    project: moz-fx-data-bq-data-science
    database: jsnyder
    table: mobile_tiles
  prod:
    project: mozdata
    database: revenue_cat3_analysis
    table: amp_rpm_forecasts_mobile
