# countries to include in forecast
countries:
  - AU
  - BR
  - CA
  - DE
  - ES
  - FR
  - GB
  - IN
  - US

output:
  test:
    output_database: jsnyder
    output_table: mobile_tiles
  prod:
    output_database: revenue_cat3_analysis
    output_table: mobile_tiles
